name: laptix
description: "Laptix: a student laptop recommendation and compatibility checker."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.13.3

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/icons/common/
    - assets/images/icons/nav/
    - assets/images/icons/home/
    - assets/images/icons/major/
    - assets/images/icons/usage/
    - assets/images/icons/budget/
    - assets/images/icons/result/
    - assets/images/icons/checker/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter-Black.ttf
          weight: 900
    - family: InterTight
      fonts:
        - asset: assets/fonts/InterTight-Regular.ttf
          weight: 400
        - asset: assets/fonts/InterTight-Medium.ttf
          weight: 500
        - asset: assets/fonts/InterTight-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/InterTight-Bold.ttf
          weight: 700
        - asset: assets/fonts/InterTight-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/InterTight-Black.ttf
          weight: 900
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist-Regular.ttf
          weight: 400
        - asset: assets/fonts/Urbanist-Medium.ttf
          weight: 500
        - asset: assets/fonts/Urbanist-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Urbanist-Bold.ttf
          weight: 700
        - asset: assets/fonts/Urbanist-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Urbanist-Black.ttf
          weight: 900

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#1E3A8A"
  adaptive_icon_foreground: "assets/icon/app_icon_foreground.png"
  remove_alpha_ios: true